FROM openjdk:8-alpine

RUN apk --update add wget tar bash make g++ readline-dev ncurses-dev git git-bash-completion ncurses


RUN apk add libtiffxx libjpeg-turbo lighttpd


https://sourceforge.net/projects/iipimage/files/IIP%20Server/iipsrv-1.1/iipsrv-1.1.tar.bz2/download
